### ISSUE TITLE
Add pre-commit support

### ISSUE THREAD

**Issue by rdturnermtl** [myint/scspell#43]
It would be nice if `scspell` supported the pre-commit tool as has been done with [codespell](https://github.com/codespell-project/codespell).

We just need to add a `.pre-commit-hooks.yaml` file at the top level. It would look something like:
```
-   id: scspell
    name: scspell
    description: 'spell checking'
    entry: scspell
    args: [--report-only]
    language: python
    types: [text]
```

The user would then need to add their source controlled dictionaries. The user `.pre-commit-config.yaml` would use a:
```
- repo: https://github.com/myint/scspell
  rev: [new version #]
  hooks:
    - id: scspell
      args: [--use-builtin-base-dict,--override-dictionary=/path/to/dictionary_file.txt]
```
Hopefully this configuration would make things "stateless" enough that it could be run across different machines without any issue.
